In [9]:
#import necessary packages
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer
from nltk.tokenize import sent_tokenize, word_tokenize
from nltk.corpus import stopwords
import nltk
import PyPDF2
import re

In [ ]:
#data = PyPDF2.PdfFileReader("resume_classification.pdf")
#data

In [ ]:
# read pdf file in pandas

In [11]:
pdfFileObj = open('Resume_template.pdf', 'rb')

In [12]:
pdfReader = PyPDF2.PdfFileReader(pdfFileObj)

In [13]:
print(pdfReader.numPages) # no of pages

2

In [14]:
pageObj = pdfReader.getPage(0)

In [15]:
print(pageObj.extractText())  # extract text from pdg

Ippenta Veronica
Certified Data Scientist
Business-minded data scientist with a demonstrated ability to deliver valuable
insights via data analytics and advanced data-driven methods with 6 months of
experience in managing data science projects.Well versed with predictive
modelling, data processing, and data mining algorithms to solve challenging
business problems.
Involved in Python open source community and passionate about brining
machine learning , deep reinforcement learning to Business
Experience
SepÕ18  -
Mar Õ 19
Data Scientist
Rubixe
¥ Fulfilled all data science duties for a high-end capital firm.
¥ Created and presented models for potential holdings and
Achieved 20% better returns vs historical
NovÕ15  -
JulÕ18
Assistant professor
Shri shrirdi sai engineering college Ð Anantapur, India
¥ 21/2 years experience in teaching and administration.
 ¥Embeddedsystems,AntennaWave&Propagation,Micro
Processors&Controllers,TelevisionEngineering.
AugÕ11 -
FebÕ12
Network Engineer
CSS CORP Ð Chennai, India
¥Expert knowledge of routers, firewalls, routing protocols, and
switches
¥Installation, repairing and maintenance of electrical and
electronic related equipments through the coordination of
maintenance teams.
¥Working on the networking devices like routers, hardware
components
Academics
DecÕ12 -
NovÕ15
Master of Technology (M.Tech In DECS)
JNTUA University
JulÕ07 Ð
MayÕ11
B.Tech in Electronics and Communication
JNTUA University
Certifications and Awards
MayÕ19
Certified Data Scientist
International Association of Business Analytics (IABAC)
SepÕ09
I was an active member of the organizing committee that
conducted EDEFT-2009- a national level paper presentation
competition
.Events and Conferences
DecÕ18
Grace Hopper Conference India -2018
, Bangalore
!"#$%&
Personal Information
Email
Jmd.verona@gmail.com
Phone
+91 7981160656
Linkedin
www.linkedin.com/in/esther-
veronica-ippenta-972a2849
Technical Skills
Python, Numpy, Pandas, Sklearn
Expert
   ! ! ! ! ! SQL
 Advanced
   ! ! ! ! ! Data Visualization, Tableau,
Matplotlib.
 Expert
   ! ! ! ! ! Machine Learning Modeling
Expert
   ! ! ! ! ! Statistics, EDA
 Expert
   ! ! ! ! ! Deep Learning, CNN
 Intermediate
   !"!"!"!"!Soft Skills
Problem Solving, Critical Thinking
Expert
   ! ! ! ! ! Creative and  Interpersonal Skills
 Expert
   !"!"!"!"!

In [ ]:
#nltk.download('punkt')
#nltk.download('stopwords')
#nltk.download('averaged_perceptron_tagger')

In [ ]:
#filtered_list

In [24]:
filtered_list=[]
def text_classification(text):
    remove_specialChar=re.sub("[^A-Za-z]+"," ",text) #remove the sp_char
    sent_token=sent_tokenize(remove_specialChar)# tokenize sentence
    word_token=word_tokenize(remove_specialChar)#tokenize words
    stop_words=set(stopwords.words('english'))#show stop words
    for word in word_token:             
          if word not in stop_words:          #exclusive stop_words
                filtered_list.append(word)
                tagged=nltk.pos_tag(filtered_list)#tagging pos
                
    
    return tagged

In [25]:
result=text_classification(pageObj.extractText())
result

[('Ippenta', 'NNP'),
 ('Veronica', 'NNP'),
 ('Certified', 'NNP'),
 ('Data', 'NNP'),
 ('Scientist', 'NNP'),
 ('Business', 'NNP'),
 ('minded', 'VBD'),
 ('data', 'NNS'),
 ('scientist', 'NN'),
 ('demonstrated', 'VBD'),
 ('ability', 'NN'),
 ('deliver', 'NN'),
 ('valuable', 'JJ'),
 ('insights', 'NNS'),
 ('via', 'IN'),
 ('data', 'NNS'),
 ('analytics', 'NNS'),
 ('advanced', 'VBD'),
 ('data', 'NNS'),
 ('driven', 'RB'),
 ('methods', 'NNS'),
 ('months', 'NNS'),
 ('experience', 'IN'),
 ('managing', 'VBG'),
 ('data', 'NNS'),
 ('science', 'NN'),
 ('projects', 'NNS'),
 ('Well', 'NNP'),
 ('versed', 'VBD'),
 ('predictive', 'JJ'),
 ('modelling', 'NN'),
 ('data', 'NNS'),
 ('processing', 'NN'),
 ('data', 'NNS'),
 ('mining', 'NN'),
 ('algorithms', 'NN'),
 ('solve', 'NN'),
 ('challenging', 'VBG'),
 ('business', 'NN'),
 ('problems', 'NNS'),
 ('Involved', 'NNP'),
 ('Python', 'NNP'),
 ('open', 'JJ'),
 ('source', 'NN'),
 ('community', 'NN'),
 ('passionate', 'VBP'),
 ('brining', 'NN'),
 ('machine', 'NN'),
 ('learning', 'VBG'),
 ('deep', 'JJ'),
 ('reinforcement', 'NN'),
 ('learning', 'VBG'),
 ('Business', 'NNP'),
 ('Experience', 'NNP'),
 ('Sep', 'NNP'),
 ('Mar', 'NNP'),
 ('Data', 'NNP'),
 ('Scientist', 'NNP'),
 ('Rubixe', 'NNP'),
 ('Fulfilled', 'NNP'),
 ('data', 'NNS'),
 ('science', 'NN'),
 ('duties', 'NNS'),
 ('high', 'JJ'),
 ('end', 'VBP'),
 ('capital', 'NN'),
 ('firm', 'NN'),
 ('Created', 'VBD'),
 ('presented', 'VBN'),
 ('models', 'NNS'),
 ('potential', 'JJ'),
 ('holdings', 'NNS'),
 ('Achieved', 'VBN'),
 ('better', 'RBR'),
 ('returns', 'NNS'),
 ('vs', 'JJ'),
 ('historical', 'JJ'),
 ('Nov', 'NNP'),
 ('Jul', 'NNP'),
 ('Assistant', 'NNP'),
 ('professor', 'NN'),
 ('Shri', 'NNP'),
 ('shrirdi', 'NN'),
 ('sai', 'NN'),
 ('engineering', 'NN'),
 ('college', 'NN'),
 ('Anantapur', 'NNP'),
 ('India', 'NNP'),
 ('years', 'NNS'),
 ('experience', 'RB'),
 ('teaching', 'VBG'),
 ('administration', 'NN'),
 ('Embeddedsystems', 'NNP'),
 ('AntennaWave', 'NNP'),
 ('Propagation', 'NNP'),
 ('Micro', 'NNP'),
 ('Processors', 'NNP'),
 ('Controllers', 'NNP'),
 ('TelevisionEngineering', 'NNP'),
 ('Aug', 'NNP'),
 ('Feb', 'NNP'),
 ('Network', 'NNP'),
 ('Engineer', 'NNP'),
 ('CSS', 'NNP'),
 ('CORP', 'NNP'),
 ('Chennai', 'NNP'),
 ('India', 'NNP'),
 ('Expert', 'NNP'),
 ('knowledge', 'NN'),
 ('routers', 'NNS'),
 ('firewalls', 'VBP'),
 ('routing', 'VBG'),
 ('protocols', 'NNS'),
 ('switches', 'NNS'),
 ('Installation', 'NNP'),
 ('repairing', 'VBG'),
 ('maintenance', 'NN'),
 ('electrical', 'JJ'),
 ('electronic', 'JJ'),
 ('related', 'JJ'),
 ('equipments', 'NNS'),
 ('coordination', 'NN'),
 ('maintenance', 'NN'),
 ('teams', 'NNS'),
 ('Working', 'VBG'),
 ('networking', 'JJ'),
 ('devices', 'NNS'),
 ('like', 'IN'),
 ('routers', 'NNS'),
 ('hardware', 'VBP'),
 ('components', 'NNS'),
 ('Academics', 'NNPS'),
 ('Dec', 'NNP'),
 ('Nov', 'NNP'),
 ('Master', 'NNP'),
 ('Technology', 'NNP'),
 ('M', 'NNP'),
 ('Tech', 'NNP'),
 ('In', 'IN'),
 ('DECS', 'NNP'),
 ('JNTUA', 'NNP'),
 ('University', 'NNP'),
 ('Jul', 'NNP'),
 ('May', 'NNP'),
 ('B', 'NNP'),
 ('Tech', 'NNP'),
 ('Electronics', 'NNP'),
 ('Communication', 'NNP'),
 ('JNTUA', 'NNP'),
 ('University', 'NNP'),
 ('Certifications', 'NNP'),
 ('Awards', 'NNP'),
 ('May', 'NNP'),
 ('Certified', 'NNP'),
 ('Data', 'NNP'),
 ('Scientist', 'NNP'),
 ('International', 'NNP'),
 ('Association', 'NNP'),
 ('Business', 'NNP'),
 ('Analytics', 'NNPS'),
 ('IABAC', 'NNP'),
 ('Sep', 'NNP'),
 ('I', 'PRP'),
 ('active', 'JJ'),
 ('member', 'NN'),
 ('organizing', 'VBG'),
 ('committee', 'NN'),
 ('conducted', 'VBN'),
 ('EDEFT', 'NNP'),
 ('national', 'JJ'),
 ('level', 'NN'),
 ('paper', 'NN'),
 ('presentation', 'NN'),
 ('competition', 'NN'),
 ('Events', 'NNS'),
 ('Conferences', 'NNPS'),
 ('Dec', 'NNP'),
 ('Grace', 'NNP'),
 ('Hopper', 'NNP'),
 ('Conference', 'NNP'),
 ('India', 'NNP'),
 ('Bangalore', 'NNP'),
 ('Personal', 'NNP'),
 ('Information', 'NNP'),
 ('Email', 'NNP'),
 ('Jmd', 'NNP'),
 ('verona', 'FW'),
 ('gmail', 'NN'),
 ('com', 'NN'),
 ('Phone', 'NNP'),
 ('Linkedin', 'NNP'),
 ('www', 'NN'),
 ('linkedin', 'NN'),
 ('com', 'NN'),
 ('esther', 'NN'),
 ('veronica', 'NN'),
 ('ippenta', 'JJ'),
 ('Technical', 'NNP'),
 ('Skills', 'NNP'),
 ('Python', 'NNP'),
 ('Numpy', 'NNP'),
 ('Pandas', 'NNP'),
 ('Sklearn', 'NNP'),
 ('Expert', 'NNP'),
 ('SQL', 'NNP'),
 ('Advanced', 'NNP'),
 ('Data', 'NNP'),
 ('Visualization', 'NNP'),
 ('Tableau', 'NNP'),
 ('Matplotlib', 'NNP'),
 ('Expert', 'NNP'),
 ('Machine', 'NNP'),
 ('Learning', 'NNP'),
 ('Modeling', 'NNP'),
 ('Expert', 'NNP'),
 ('Statistics', 'NNP'),
 ('EDA', 'NNP'),
 ('Expert', 'NNP'),
 ('Deep', 'NNP'),
 ('Learning', 'NNP'),
 ('CNN', 'NNP'),
 ('Intermediate', 'NNP'),
 ('Soft', 'NNP'),
 ('Skills', 'NNP'),
 ('Problem', 'NNP'),
 ('Solving', 'NNP'),
 ('Critical', 'NNP'),
 ('Thinking', 'NNP'),
 ('Expert', 'NNP'),
 ('Creative', 'NNP'),
 ('Interpersonal', 'NNP'),
 ('Skills', 'NNP'),
 ('Expert', 'NNP')]

In [33]:
#pip install spacy

In [4]:
# use spacy for NER-classifier
import spacy 
from spacy import displacy
spacy.__version__

In [34]:
#!python -m spacy download en_core_web_sm

In [26]:
nlp=spacy.load("en_core_web_sm")

In [41]:
doc=nlp(str(filtered_list))
entities=[]
lables=[]
for i in doc.ents:
    entities.append(i)
    lables.append(i.label_)
print([(word, word.ent_type_) for word in doc if word.ent_type_])
df=pd.DataFrame({'Entities':entities,"Labels":lables})

df

[(Ippenta, 'PERSON'), (', 'DATE'), (months, 'DATE'), (', 'DATE'), (Mar, 'PERSON'), (Jul, 'PERSON'), (India, 'GPE'), (', 'DATE'), (years, 'DATE'), (', 'DATE'), (Network, 'PERSON'), (India, 'GPE'), (Jul, 'PERSON'), (Hopper, 'ORG'), (India, 'GPE'), (Email, 'PERSON'), (Jmd, 'PERSON'), (verona, 'PERSON'), (Linkedin, 'PERSON'), (Sklearn, 'PERSON'), (Tableau, 'PERSON'), (Matplotlib, 'PERSON'), (EDA, 'ORG'), (CNN, 'ORG')]

          Entities  Labels
0        (Ippenta)  PERSON
1   (', months, ')    DATE
2            (Mar)  PERSON
3            (Jul)  PERSON
4          (India)     GPE
5    (', years, ')    DATE
6        (Network)  PERSON
7          (India)     GPE
8            (Jul)  PERSON
9         (Hopper)     ORG
10         (India)     GPE
11         (Email)  PERSON
12           (Jmd)  PERSON
13        (verona)  PERSON
14      (Linkedin)  PERSON
15       (Sklearn)  PERSON
16       (Tableau)  PERSON
17    (Matplotlib)  PERSON
18           (EDA)     ORG
19           (CNN)     ORG